# Numpy

> A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

### 1. Initialization

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [7]:
import numpy as np 

#---- 1 dimension array : vector
a = np.array([1, 2, 3])
print(type(a))
print(a.shape)

#---- 2 dimensions array: matrix
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)

#---- 3 dimensions array: tensor
c = np.array([[[1, 2, 1], [3, 4, 3]], [[5, 6, 5], [9, 10, 9]]]) 
print(c.shape) # 2-2-3 : rows-colums-heights 

<class 'numpy.ndarray'>
(3,)
(2, 3)
(2, 2, 3)


Other ways to create arrays:

In [1]:
import numpy as np

#======== Create all zeros array
a = np.zeros((2,2))
print(a)

[[ 0.  0.]
 [ 0.  0.]]


In [3]:
#========= Create an array of all ones
b = np.ones((1, 2))
print(b)

[[ 1.  1.]]


In [5]:
#========= Create constant array
c = np.full((2,2), 7)
print(c)

[[ 7.  7.]
 [ 7.  7.]]


In [6]:
#========== Create identity matrix
d = np.eye(2)
print(d)

[[ 1.  0.]
 [ 0.  1.]]


In [8]:
#=========== Create random array
e = np.random.random((2,2))
print(e)

[[0.62824159 0.11123824]
 [0.07987363 0.42031607]]


In [12]:
#=========== create array with arrange
f = np.arange(1, 10)
print(f)
g = np.arange(1, 10, 2)
print(g)

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


### 2. Indexing

In [8]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


In [9]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [11]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

[1 4 5]
[1 4 5]


In [12]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


**Boolean array indexing** Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition.


In [13]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"
        

[[False False]
 [ True  True]
 [ True  True]]


In [14]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

[3 4 5 6]


In [15]:
# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[3 4 5 6]


### 3. Datatypes

Numpy tries to guess a datatype when we create an array. But we can define explicitly spcecify the datatype

In [17]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int64
float64
int64


In [19]:
np.dtype

numpy.dtype

### 4. Array math

#### 4.1 Basic math operations: add, subtract, multiple, divide

In [1]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


Notices: multiple (*) is elementwise multiplication, __not matrix multiplication__

we use __dot()__ to do matrix multiplication

In [2]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


##### 4.2 Sum elements of array

In [3]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


##### 4.3 Transpose 

In [1]:
import numpy as np

#---------- 2d shape
arr = np.array([[1, 2], [3, 4]])
print(arr)
### Transpose of arr is arr.T
print(arr.T)

#---------- 1d shape (vector)
arr1 = np.array([1, 2, 3])
print(arr1)
print(arr1.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


##### 4.4 Norm

In [2]:
from numpy import linalg
A = np.array([1, 2, 3, 2, 3, 4])
linalg.norm(A)

6.5574385243020004

### 5. Broadcasting

In [15]:
import numpy as np
ar = np.array([1,2,3])
print(ar + 2)

[3 4 5]


In [19]:
numbers_2D = np.asarray([
    [4, 5, 6], 
    [7, 8, 9]
])
print(numbers_2D + 20)
print(numbers_2D * 2)

[[24 25 26]
 [27 28 29]]
[[ 8 10 12]
 [14 16 18]]


In [20]:
x = np.array([
    [6, 9, 10],
    [15, 18, 20],
])
y = np.array([
    [2],
    [4],
])
x + y

array([[ 8, 11, 12],
       [19, 22, 24]])

In [2]:
import numpy as np
a = np.arange(1, 5)
print(a.shape)
print(a.T.shape)


(4,)
(4,)
